# Generated by Django 6.0.6 on 2026-06-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('profile', models.CharField(help_text='e.g., Electricians, Plumbers, Teachers', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('asset', models.FileField(blank=True, help_text='Upload image/video or leave blank to generate from text', null=True, upload_to='ad_assets/')),
                ('text_content', models.TextField(blank=True, help_text='Text content for ad generation')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('admin_feedback', models.TextField(blank=True)),
                ('final_asset', models.FileField(blank=True, null=True, upload_to='final_ads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='AdIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.FileField(blank=True, null=True, upload_to='iteration_assets/')),
                ('feedback', models.TextField(blank=True)),
                ('created_by', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='ads.ad')),
            ],
        ),
        migrations.CreateModel(
            name='TargetArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'unique_together': {('state', 'city', 'locality')},
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='target_areas',
            field=models.ManyToManyField(blank=True, to='ads.targetarea'),
        ),
        migrations.AddField(
            model_name='ad',
            name='target_audiences',
            field=models.ManyToManyField(blank=True, to='ads.targetaudience'),
        ),
    ]
