# Generated by Django 6.0.5 on 2026-06-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='generation_error',
            field=models.TextField(blank=True, help_text='Error message from video generation, if any'),
        ),
    ]
