# Generated by Django 6.0.5 on 2026-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='languages',
            field=models.ManyToManyField(blank=True, to='ads.language'),
        ),
    ]
