# Generated by Django 6.0.5 on 2026-06-17 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_language_ad_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdLanguageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, help_text='Prompt used for video generation')),
                ('asset', models.FileField(blank=True, null=True, upload_to='final_ads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_assets', to='ads.ad')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.language')),
            ],
            options={
                'unique_together': {('ad', 'language')},
            },
        ),
    ]
