# Generated by Django 6.0.5 on 2026-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_adlanguageasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, help_text='Campaign end date', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Campaign start date', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
