# Generated by Django 6.0.5 on 2026-06-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_developer'),
        ('ads', '0006_ad_schedule_and_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('app_type', models.CharField(choices=[('website', 'Website'), ('mobile', 'Mobile App')], default='website', max_length=20)),
                ('app_url', models.URLField(blank=True)),
                ('api_key', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='accounts.developer')),
            ],
        ),
        migrations.CreateModel(
            name='AdDeveloperPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_pushes', to='ads.ad')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_pushes', to='ads.developerapp')),
            ],
            options={
                'verbose_name': 'Ad to Developer Push',
                'verbose_name_plural': 'Ad to Developer Pushes',
                'unique_together': {('ad', 'app')},
            },
        ),
    ]
