# Generated by Django 6.0.5 on 2026-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_apiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='content_size',
            field=models.CharField(blank=True, default='', help_text='Desired dimensions e.g. 1920x1080, 1080x1920', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='content_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image')], default='video', help_text='Whether to generate a video or image ad', max_length=10),
        ),
    ]
