# Generated by Django 6.0.5 on 2026-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_add_content_type_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerapp',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developerapp',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
