# Generated by Django 6.0.5 on 2026-07-03 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_developerapp_description_developerapp_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='generated_media/')),
                ('prompt', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Media',
                'verbose_name_plural': 'Generated Media',
                'ordering': ['-created_at'],
            },
        ),
    ]
