# Generated by Django 6.0.5 on 2026-07-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_generatedmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='VideoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, help_text='Display name of the person who left feedback', max_length=255)),
                ('created_by', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='client', max_length=20)),
                ('comment', models.TextField()),
                ('timestamp_seconds', models.FloatField(blank=True, help_text='Video timestamp in seconds for annotation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_feedback', to='ads.ad')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
