# Generated by Django 6.0.5 on 2026-07-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_ad_status_videofeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofeedback',
            name='language_asset',
            field=models.ForeignKey(blank=True, help_text='Specific language asset this feedback refers to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_feedback', to='ads.adlanguageasset'),
        ),
    ]
