# Generated by Django 6.0.5 on 2026-07-06 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_videofeedback_language_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-generated from first prompt', max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Session settings: width, height, duration, model, style, etc.')),
                ('current_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creative Session',
                'verbose_name_plural': 'Creative Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('generate', 'Generation'), ('edit_prompt', 'Prompt Edit'), ('edit_settings', 'Settings Change'), ('delete_asset', 'Asset Deletion')], max_length=20)),
                ('prompt', models.TextField(blank=True, help_text='Prompt at the time of event')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Settings snapshot at time of event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_events', to='ads.generatedmedia')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ads.creativesession')),
            ],
            options={
                'verbose_name': 'Session Event',
                'verbose_name_plural': 'Session Events',
                'ordering': ['created_at'],
            },
        ),
    ]
