# Generated by Django 6.0.5 on 2026-07-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_creativesession_creativesessionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativesessionevent',
            name='file',
            field=models.URLField(blank=True, default='', help_text='Direct file URL for events without GeneratedMedia (e.g. merged videos)', max_length=500),
        ),
        migrations.AlterField(
            model_name='creativesessionevent',
            name='event_type',
            field=models.CharField(choices=[('generate', 'Generation'), ('edit_prompt', 'Prompt Edit'), ('edit_settings', 'Settings Change'), ('delete_asset', 'Asset Deletion'), ('merge', 'Video Merge')], max_length=20),
        ),
    ]
