# Generated by Django 6.0.5 on 2026-07-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_creditusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='credit_cost',
            field=models.IntegerField(default=0, help_text='Credits consumed (0 = free request)'),
        ),
    ]
