# Generated by Django 6.0.5 on 2026-06-25 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_balance',
            field=models.IntegerField(default=50, help_text='Free credits given on registration'),
        ),
        migrations.AddField(
            model_name='manager',
            name='credit_balance',
            field=models.IntegerField(default=100, help_text='Free credits given on account creation'),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='accounts.client')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='accounts.manager')),
            ],
        ),
    ]
