# Generated by Django 6.0.5 on 2026-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_set_default_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='last_daily_credits_at',
            field=models.DateTimeField(blank=True, help_text='Last time daily free credits were given', null=True),
        ),
    ]
