# Generated by Django 6.0.5 on 2026-06-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_manager_last_daily_credits_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='credit_balance',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='credit_balance',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='last_daily_credits_at',
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
    ]
