# Generated by Django 6.0.5 on 2026-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_client_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='google_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
